COUNTRIES = {"afghanistan": "AF",
             "albania": "AL",
             "algeria": "DZ",
             "american samoa": "AS",
             "andorra": "AD",
             "angola": "AO",
             "anguilla": "AI",
             "antarctica": "AQ",
             "antigua and barbuda": "AG",
             "argentina": "AR",
             "armenia": "AM",
             "aruba": "AW",
             "australia": "AU",
             "austria": "AT",
             "azerbaijan": "AZ",
             "bahamas": "BS",
             "bahrain": "BH",
             "bangladesh": "BD",
             "barbados": "BB",
             "belarus": "BY",
             "belgium": "BE",
             "belize": "BZ",
             "benin": "BJ",
             "bermuda": "BM",
             "bhutan": "BT",
             "bolivia": "BO",
             "bosnia and Herzegovina": "BA",
             "botswana": "BW",
             "bouvet island": "BV",
             "brazil": "BR",
             "british indian ocean territory": "IO",
             "brunei Darussalam": "BN",
             "bulgaria": "BG",
             "burkina faso": "BF",
             "burundi": "BI",
             "cambodia": "KH",
             "cameroon": "CM",
             "canada": "CA",
             "cape Verde": "CV",
             "cayman islands": "KY",
             "central african republic": "CF",
             "chad": "TD",
             "chile": "CL",
             "china": "CN",
             "christmas island": "CX",
             "cocos islands": "CC",
             "colombia": "CO",
             "comoros": "KM",
             "congo": "CG",
             "cook islands": "CK",
             "costa rica": "CR",
             "cote D'Ivoire": "CI",
             "croatia": "HR",
             "cuba": "CU",
             "cyprus": "CY",
             "czech republic": "CZ",
             "czechoslovakia": "CS",
             "denmark": "DK",
             "djibouti": "DJ",
             "dominica": "DM",
             "dominican republic": "DO",
             "east timor": "TP",
             "ecuador": "EC",
             "egypt": "EG",
             "el salvador": "SV",
             "equatorial guinea": "GQ",
             "eritrea": "ER",
             "estonia": "EE",
             "ethiopia": "ET",
             "falkland islands": "FK",
             "faroe islands": "FO",
             "fiji": "FJ",
             "finland": "FI",
             "france": "FR",
             "french guiana": "GF",
             "french polynesia": "PF",
             "french southern territories": "TF",
             "gabon": "GA",
             "gambia": "GM",
             "georgia": "GE",
             "germany": "DE",
             "ghana": "GH",
             "gibraltar": "GI",
             "great Britain": "GB",
             "greece": "GR",
             "greenland": "GL",
             "grenada": "GD",
             "guadeloupe": "GP",
             "guam": "GU",
             "guatemala": "GT",
             "guinea": "GN",
             "guyana": "GY",
             "haiti": "HT",
             "heard and mcdonald islands": "HM",
             "honduras": "HN",
             "hong kong": "HK",
             "hungary": "HU",
             "iceland": "IS",
             "india": "IN",
             "indonesia": "ID",
             "iran": "IR",
             "iraq": "IQ",
             "ireland": "IE",
             "israel": "IL",
             "italy": "IT",
             "jamaica": "JM",
             "japan": "JP",
             "jordan": "JO",
             "kazakhstan": "KZ",
             "kenya": "KE",
             "kiribati": "KI",
             "north korea": "KP",
             "south korea": "KR",
             "kuwait": "KW",
             "kyrgyzstan": "KG",
             "laos": "LA",
             "latvia": "LV",
             "lebanon": "LB",
             "lesotho": "LS",
             "liberia": "LR",
             "libya": "LY",
             "liechtenstein": "LI",
             "lithuania": "LT",
             "luxembourg": "LU",
             "macau": "MO",
             "macedonia": "MK",
             "madagascar": "MG",
             "malawi": "MW",
             "malaysia": "MY",
             "maldives": "MV",
             "mali": "ML",
             "malta": "MT",
             "marshall islands": "MH",
             "martinique": "MQ",
             "mauritania": "MR",
             "mauritius": "MU",
             "mayotte": "YT",
             "mexico": "MX",
             "micronesia": "FM",
             "moldova": "MD",
             "monaco": "MC",
             "mongolia": "MN",
             "montenegro": "ME",
             "montserrat": "MS",
             "morocco": "MA",
             "mozambique": "MZ",
             "myanmar": "MM",
             "namibia": "NA",
             "nauru": "NR",
             "nepal": "NP",
             "netherlands": "NL",
             "netherlands antilles": "AN",
             "neutral Zone": "NT",
             "new caledonia": "NC",
             "new Zealand": "NZ",
             "nicaragua": "NI",
             "niger": "NE",
             "nigeria": "NG",
             "niue": "NU",
             "norfolk island": "NF",
             "northern mariana islands": "MP",
             "norway": "NO",
             "oman": "OM",
             "pakistan": "PK",
             "palau": "PW",
             "panama": "PA",
             "papua New guinea": "PG",
             "paraguay": "PY",
             "peru": "PE",
             "philippines": "PH",
             "pitcairn": "PN",
             "poland": "PL",
             "portugal": "PT",
             "puerto rico": "PR",
             "qatar": "QA",
             "reunion": "RE",
             "romania": "RO",
             "russian federation": "RU",
             "rwanda": "RW",
             "saint": "LC",
             "saudi arabia": "SA",
             "senegal": "SN",
             "serbia": "RS",
             "seychelles": "SC",
             "sierra leone": "SL",
             "singapore": "SG",
             "slovak republic": "SK",
             "slovenia": "SI",
             "solomon islands": "Sb",
             "somalia": "SO",
             "south africa": "ZA",
             "spain": "ES",
             "sri lanka": "LK",
             "st. Helena": "SH",
             "st. pierre and miquelon": "PM",
             "sudan": "SD",
             "suriname": "SR",
             "svalbard and jan mayen islands": "SJ",
             "swaziland": "SZ",
             "sweden": "SE",
             "switzerland": "CH",
             "syria": "SY",
             "taiwan": "TW",
             "tajikistan": "TJ",
             "tanzania": "TZ",
             "thailand": "TH",
             "togo": "TG",
             "tokelau": "TK",
             "tonga": "TO",
             "trinidad and tobago": "TT",
             "tunisia": "TN",
             "turkey": "TR",
             "turkmenistan": "TM",
             "turks and caicos islands": "TC",
             "tuvalu": "TV",
             "uS minor outlying islands": "UM",
             "ussr": "SU",
             "uganda": "UG",
             "ukraine": "UA",
             "united arab emirates": "AE",
             "united kingdom": "UK",
             "united states": "US",
             "uruguay": "UY",
             "uzbekistan": "UZ",
             "vanuatu": "VU",
             "vatican city state": "VA",
             "venezuela": "VE",
             "vietnam": "VN",
             "virgin islands": "VG",
             "virgin islands": "VI",
             "wallis and futuna islands": "WF",
             "western sahara": "EH",
             "yemen": "YE",
             "yugoslavia": "YU",
             "zaire": "ZR",
             "zambia": "ZM",
             "zimbabwe": "ZW"
             }

AGES = ["16-18", "19-22", "23-30", "31-40", "41-50", "50+"]
GENDERS = ['male', 'female']
